# Generated by Django 3.2.5 on 2022-07-29 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Monthly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Time_Period', models.CharField(max_length=100)),
                ('Area', models.CharField(max_length=250)),
                ('Sector', models.CharField(max_length=250)),
                ('Project', models.CharField(max_length=100)),
                ('Community', models.CharField(max_length=250)),
                ('Results_Level', models.CharField(max_length=50)),
                ('Frequency', models.CharField(max_length=100)),
                ('Indicator_ID', models.CharField(max_length=50)),
                ('Indicator', models.CharField(max_length=300)),
                ('Activity', models.CharField(max_length=300)),
                ('Unit', models.CharField(max_length=100)),
                ('Actual', models.FloatField()),
                ('Male_Under5', models.FloatField()),
                ('Female_Under5', models.FloatField()),
                ('Male_Above5', models.FloatField()),
                ('Female_Above5', models.FloatField()),
                ('Male_PWD', models.FloatField()),
                ('Female_PWD', models.FloatField()),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Target',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Time_Period', models.CharField(max_length=100)),
                ('Area', models.CharField(max_length=250)),
                ('Sector', models.CharField(max_length=250)),
                ('Project', models.CharField(max_length=100)),
                ('Community', models.CharField(max_length=250)),
                ('Results_Level', models.CharField(max_length=50)),
                ('Frequency', models.CharField(max_length=100)),
                ('Indicator_ID', models.CharField(max_length=50)),
                ('Indicator', models.CharField(max_length=300)),
                ('Activity', models.CharField(max_length=300)),
                ('Unit', models.CharField(max_length=100)),
                ('Target', models.FloatField()),
            ],
        ),
    ]
